/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ConfigFormRender: typeof import('./src/views/cook/components/RightArea/ConfigFormRender.vue')['default']
    DraggableArea: typeof import('./src/views/cook/components/MiddleArea/DraggableArea.vue')['default']
    EditorStringToCode: typeof import('./src/components/FormRender/components/EditorStringToCode.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDialogv: typeof import('element-plus/es')['ElDialogv']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    FormRender: typeof import('./src/components/FormRender/FormRender.vue')['default']
    IconInput: typeof import('./src/components/MaterialIcons/IconInput.vue')['default']
    IconSwitch: typeof import('./src/components/MaterialIcons/IconSwitch.vue')['default']
    IEpDelete: typeof import('~icons/ep/delete')['default']
    IEpView: typeof import('~icons/ep/view')['default']
    LeftArea: typeof import('./src/views/cook/components/LeftArea.vue')['default']
    MiddleArea: typeof import('./src/views/cook/components/MiddleArea/index.vue')['default']
    RightArea: typeof import('./src/views/cook/components/RightArea/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TopArea: typeof import('./src/views/cook/components/TopArea.vue')['default']
  }
}
