/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    copy: typeof import('./src/views/cook/components/MiddleArea/index copy.vue')['default']
    DraggableArea: typeof import('./src/views/cook/components/MiddleArea/DraggableArea.vue')['default']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    IconInput: typeof import('./src/components/icon/IconInput.vue')['default']
    LeftArea: typeof import('./src/views/cook/components/LeftArea.vue')['default']
    MiddleArea: typeof import('./src/views/cook/components/MiddleArea/index.vue')['default']
    RightArea: typeof import('./src/views/cook/components/RightArea.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TopArea: typeof import('./src/views/cook/components/TopArea.vue')['default']
  }
}
