name: Deploy Docs & Demo (pnpm)

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ 检出仓库
      - uses: actions/checkout@v4

      # 2️⃣ 安装 pnpm
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      # 3️⃣ 设置 Node 版本
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      # 4️⃣ 安装依赖
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      # 5️⃣ 构建 Demo
      - name: Build demo
        run: pnpm run build --filter demo

      # 6️⃣ 构建 VitePress 文档
      - name: Build docs
        run: pnpm run docs:build

      # 7️⃣ 合并 demo 到文档输出目录
      - name: Copy demo to docs output
        run: |
          mkdir -p docs/.vitepress/dist/demo
          cp -r demo/dist/* docs/.vitepress/dist/demo/

      # 8️⃣ 部署到 GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/.vitepress/dist
